import type { EditorThemeClasses } from "lexical";

export const editorTheme: EditorThemeClasses = {
  paragraph: "mt-0.5 text-sm text-foreground",
  heading: {
    h1: "mt-6 text-2xl font-semibold text-foreground",
    h2: "mt-5 text-xl font-semibold text-foreground",
    h3: "mt-4 text-lg font-medium text-foreground",
  },
  quote:
    "mt-3 border-l-2 border-white/[0.06] pl-4 text-sm text-muted-foreground italic",
  list: {
    ul: "mt-0.5 list-disc pl-6 text-sm",
    ol: "mt-0.5 list-decimal pl-6 text-sm",
    listitem: "mt-0.5 text-sm",
    nested: {
      listitem: "list-none",
    },
    listitemChecked:
      "editor-checklist-checked relative mt-0.5 list-none pl-6 line-through text-muted-foreground",
    listitemUnchecked:
      "editor-checklist-unchecked relative mt-0.5 list-none pl-6",
    olDepth: ["list-decimal", "list-[lower-alpha]", "list-[lower-roman]"],
  },
  code: "mt-3 block bg-muted rounded-sm p-4 font-mono text-sm overflow-x-auto",
  codeHighlight: {
    atrule: "text-primary",
    attr: "text-primary",
    boolean: "text-code-constant",
    builtin: "text-code-builtin",
    cdata: "text-muted-foreground",
    char: "text-code-string",
    class: "text-code-type",
    "class-name": "text-code-type",
    comment: "text-muted-foreground",
    constant: "text-code-constant",
    deleted: "text-destructive",
    doctype: "text-muted-foreground",
    entity: "text-code-constant",
    function: "text-primary",
    important: "text-code-constant",
    inserted: "text-code-string",
    keyword: "text-code-keyword",
    namespace: "text-muted-foreground",
    number: "text-code-constant",
    operator: "text-code-keyword",
    prolog: "text-muted-foreground",
    property: "text-primary",
    punctuation: "text-muted-foreground",
    regex: "text-code-constant",
    selector: "text-code-string",
    string: "text-code-string",
    symbol: "text-code-constant",
    tag: "text-code-constant",
    url: "text-primary",
    variable: "text-code-constant",
  },
  text: {
    bold: "font-bold",
    italic: "italic",
    underline: "underline",
    strikethrough: "line-through",
    underlineStrikethrough: "underline line-through",
    code: "bg-muted px-1.5 py-0.5 text-sm font-mono rounded-sm",
  },
  link: "text-accent underline cursor-pointer hover:text-accent/80",
  horizontalRule: "mt-3 mb-3 border-t border-white/[0.06]",
};
