import type { EditorThemeClasses } from "lexical";

export const editorTheme: EditorThemeClasses = {
  paragraph: "mt-0.5 text-sm text-foreground leading-relaxed",
  heading: {
    h1: "mt-6 text-2xl font-semibold text-foreground",
    h2: "mt-5 text-xl font-semibold text-foreground",
    h3: "mt-4 text-lg font-medium text-foreground",
  },
  quote:
    "mt-3 border-l-2 border-white/[0.12] pl-4 text-sm text-muted-foreground italic",
  list: {
    ul: "mt-0.5 list-disc pl-6 text-sm",
    ol: "mt-0.5 list-decimal pl-6 text-sm",
    listitem: "mt-0.5 text-sm",
    nested: {
      listitem: "list-none",
    },
    listitemChecked:
      "relative mt-0.5 list-none pl-6 line-through text-muted-foreground",
    listitemUnchecked: "relative mt-0.5 list-none pl-6",
    olDepth: ["list-decimal", "list-[lower-alpha]", "list-[lower-roman]"],
  },
  code: "mt-3 block bg-muted rounded-sm p-4 font-mono text-sm overflow-x-auto",
  codeHighlight: {
    atrule: "text-[oklch(0.74_0.032_248)]",
    attr: "text-[oklch(0.74_0.032_248)]",
    boolean: "text-[oklch(0.65_0.15_25)]",
    builtin: "text-[oklch(0.70_0.08_200)]",
    cdata: "text-muted-foreground",
    char: "text-[oklch(0.70_0.12_150)]",
    class: "text-[oklch(0.75_0.08_80)]",
    "class-name": "text-[oklch(0.75_0.08_80)]",
    comment: "text-muted-foreground",
    constant: "text-[oklch(0.65_0.15_25)]",
    deleted: "text-destructive",
    doctype: "text-muted-foreground",
    entity: "text-[oklch(0.65_0.15_25)]",
    function: "text-[oklch(0.74_0.032_248)]",
    important: "text-[oklch(0.65_0.15_25)]",
    inserted: "text-[oklch(0.70_0.12_150)]",
    keyword: "text-[oklch(0.65_0.12_300)]",
    namespace: "text-muted-foreground",
    number: "text-[oklch(0.65_0.15_25)]",
    operator: "text-[oklch(0.65_0.12_300)]",
    prolog: "text-muted-foreground",
    property: "text-[oklch(0.74_0.032_248)]",
    punctuation: "text-muted-foreground",
    regex: "text-[oklch(0.65_0.15_25)]",
    selector: "text-[oklch(0.70_0.12_150)]",
    string: "text-[oklch(0.70_0.12_150)]",
    symbol: "text-[oklch(0.65_0.15_25)]",
    tag: "text-[oklch(0.65_0.15_25)]",
    url: "text-[oklch(0.74_0.032_248)]",
    variable: "text-[oklch(0.65_0.15_25)]",
  },
  text: {
    bold: "font-bold",
    italic: "italic",
    underline: "underline",
    strikethrough: "line-through",
    underlineStrikethrough: "underline line-through",
    code: "bg-muted px-1.5 py-0.5 text-sm font-mono rounded-sm",
  },
  link: "text-accent underline cursor-pointer hover:text-accent/80",
  horizontalRule: "mt-3 mb-3 border-t border-white/[0.06]",
};
