-- RPC function for the Feedback Digest automation.
-- Returns event counts from the last 7 days, excluding events generated by
-- automation test users (identified by email in the excluded_emails parameter).

create or replace function usage_event_counts_7d(
  excluded_emails text[] default '{}'::text[]
)
returns table(event_name text, event_count bigint)
language sql
stable
security definer
as $$
  select
    ue.event_name,
    count(*)::bigint as event_count
  from usage_events ue
  where ue.created_at >= now() - interval '7 days'
    and ue.user_id not in (
      select au.id
      from auth.users au
      where au.email = any(excluded_emails)
    )
  group by ue.event_name
  order by event_count desc;
$$;
